projects:
  amplifynotetaker:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: sirt4i3ywjfuplcz63ix5zbv7m
      endpoints:
        prod: >-
          https://3ovwymanlzfr7cmjhsu6qcvp3e.appsync-api.us-east-1.amazonaws.com/graphql
